--CREATE ROLE smfd WITH LOGIN PASSWORD 'smfd';
--CREATE DATABASE smfd OWNER smfd ENCODING 'UTF8' CONNECTION LIMIT 25;

-- utils
CREATE SCHEMA IF NOT EXISTS module__utils AUTHORIZATION smfd;
CREATE SCHEMA IF NOT EXISTS smfd_user AUTHORIZATION smfd;
CREATE SCHEMA IF NOT EXISTS smfd_settings AUTHORIZATION smfd;
CREATE SCHEMA IF NOT EXISTS smfd_data AUTHORIZATION smfd;
CREATE SCHEMA IF NOT EXISTS smfd_data_partitions AUTHORIZATION smfd;
CREATE SCHEMA IF NOT EXISTS smfd_advert AUTHORIZATION smfd;
CREATE SCHEMA IF NOT EXISTS smfd_task_manager AUTHORIZATION smfd;

-- dblink
CREATE SCHEMA IF NOT EXISTS module_dblink AUTHORIZATION smfd;
CREATE EXTENSION IF NOT EXISTS dblink SCHEMA module_dblink;

-- pgcrypto
CREATE SCHEMA IF NOT EXISTS module_pgcrypto AUTHORIZATION smfd;
CREATE EXTENSION IF NOT EXISTS pgcrypto SCHEMA module_pgcrypto;

-- hstore
CREATE SCHEMA IF NOT EXISTS module_hstore AUTHORIZATION smfd;
CREATE EXTENSION IF NOT EXISTS hstore SCHEMA module_hstore;

CREATE TYPE public.S_KEY_VALUE_PAIR AS (
	key   TEXT,
	value TEXT
);
